-- =====================================================================
-- 07_disease.sql — রোগ ও মৃত্যুর কারণ (গ্লোবাল সিড)
--
-- is_notifiable = সরকারিভাবে জানানো বাধ্যতামূলক এমন রোগ। বাংলাদেশে
-- প্রাণিসম্পদ অধিদপ্তর (DLS) ও আন্তর্জাতিক WOAH তালিকা অনুসারে
-- সীমান্ত-অতিক্রমী ও জনস্বাস্থ্যঝুঁকির রোগগুলো চিহ্নিত করা হয়েছে।
-- আইনি তালিকা সময়ে সময়ে বদলায়, তাই এটা সম্পাদনযোগ্য — সন্দেহ হলে
-- স্থানীয় উপজেলা প্রাণিসম্পদ কর্মকর্তার সাথে যাচাই করুন।
-- =====================================================================

create temporary table _dz (
  disease_code text, name_bn text, name_en text, cause_type text,
  notifiable boolean, zoonotic boolean, contagious boolean,
  signs_bn text, prevention_bn text, species_codes text[], sort_order int
);

insert into _dz values
-- ═══════ মুরগির ভাইরাসজনিত ═══════
('ND','রানীক্ষেত','Newcastle Disease (ND)','viral',true,false,true,
 'ঝিমানো, সবুজ পাতলা পায়খানা, শ্বাসকষ্ট, ঘাড় বাঁকা হয়ে যাওয়া, হঠাৎ ব্যাপক মৃত্যু',
 'সময়মতো BCRDV ও RDV টিকা; বায়োসিকিউরিটি',
 array['CHICKEN','TURKEY','GUINEA_FOWL','PIGEON'],10),
('IBD','গামবোরো','Infectious Bursal Disease (Gumboro)','viral',false,false,true,
 'সাদা-পানির মতো পায়খানা, নিজের পায়ুপথে ঠোকর, ঝিমানো, ৩–৬ সপ্তাহে মৃত্যু',
 '১১ ও ১৮ দিনে গামবোরো টিকা; শেড শুকনো রাখা',
 array['CHICKEN'],11),
('IB','ইনফেকশাস ব্রংকাইটিস','Infectious Bronchitis','viral',false,false,true,
 'কাশি, হাঁচি, নাক দিয়ে পানি, লেয়ারে ডিম কমে ও খোসা নরম হয়',
 'IB টিকা; ঠান্ডা বাতাস ও ধুলা নিয়ন্ত্রণ',
 array['CHICKEN'],12),
('AI','বার্ড ফ্লু (এভিয়ান ইনফ্লুয়েঞ্জা)','Avian Influenza','viral',true,true,true,
 'হঠাৎ প্রচুর মৃত্যু, ঝুঁটি ও পা নীলচে, মুখ-চোখ ফোলা',
 'জৈব নিরাপত্তা, বাইরের পাখি ঠেকানো, সন্দেহ হলেই সরকারি অফিসে খবর দেওয়া বাধ্যতামূলক',
 array['CHICKEN','DUCK','MUSCOVY','GOOSE','QUAIL','TURKEY','GUINEA_FOWL','PIGEON'],13),
('MAREK','মারেক্স','Marek''s Disease','viral',false,false,true,
 'পা বা ডানা অবশ, ওজন কমা, ৮–২০ সপ্তাহে মৃত্যু',
 'হ্যাচারিতে একদিনেই মারেক্স টিকা',array['CHICKEN'],14),
('FOWL_POX','ফাউল পক্স (গুটি বসন্ত)','Fowl Pox','viral',false,false,true,
 'ঝুঁটি, মুখ ও পায়ের চামড়ায় গুটি; মুখের ভেতরে হলে খাওয়া বন্ধ',
 'ডানার চামড়ায় (wing web) টিকা; মশা নিয়ন্ত্রণ',
 array['CHICKEN','TURKEY','PIGEON'],15),
('ILT','ইনফেকশাস লেরিংগোট্রাকিয়াইটিস','Infectious Laryngotracheitis','viral',false,false,true,
 'রক্তমিশ্রিত কফ, গলা টেনে শ্বাস নেওয়া','টিকা ও বায়োসিকিউরিটি',array['CHICKEN'],16),
('EDS','ডিম কমে যাওয়া সিনড্রোম','Egg Drop Syndrome','viral',false,false,true,
 'হঠাৎ ডিম কমে যাওয়া, খোসাবিহীন বা নরম খোসার ডিম',
 '১৪–১৬ সপ্তাহে EDS টিকা',array['CHICKEN','DUCK'],17),
('CIA','চিকেন ইনফেকশাস অ্যানিমিয়া','Chicken Infectious Anaemia','viral',false,false,true,
 'রক্তশূন্যতা, ফ্যাকাশে ঝুঁটি, বৃদ্ধি থেমে যাওয়া','ব্রিডারে টিকা',array['CHICKEN'],18),
('DUCK_PLAGUE','ডাক প্লেগ','Duck Plague (Duck Viral Enteritis)','viral',false,false,true,
 'হঠাৎ মৃত্যু, সবুজ-রক্তমিশ্রিত পায়খানা, চোখে পানি',
 'ডাক প্লেগ টিকা ৩–৪ সপ্তাহে, পরে বুস্টার',array['DUCK','MUSCOVY','GOOSE'],19),
('DUCK_HEPATITIS','ডাক ভাইরাল হেপাটাইটিস','Duck Viral Hepatitis','viral',false,false,true,
 'বাচ্চা হাঁসে হঠাৎ মৃত্যু, মাথা পিছনে বেঁকে যাওয়া','টিকা ও পরিষ্কার পানি',array['DUCK'],20),
-- ═══════ মুরগির ব্যাকটেরিয়াজনিত ═══════
('CRD','সিআরডি (মাইকোপ্লাজমা)','Chronic Respiratory Disease (CRD)','bacterial',false,false,true,
 'নাক ডাকার মতো শব্দ, হাঁচি, চোখে ফেনা, বৃদ্ধি কমে যাওয়া',
 'পরিষ্কার শুকনো লিটার, অ্যামোনিয়া কমানো, ভালো বায়ু চলাচল',
 array['CHICKEN','TURKEY','QUAIL'],30),
('SALMONELLA','সালমোনেলা / পুলোরাম','Salmonellosis (Pullorum)','bacterial',false,true,true,
 'বাচ্চায় সাদা আঠালো পায়খানা, নাভির কাছে ফোলা, বেশি মৃত্যু',
 'পরিষ্কার হ্যাচারি, ডিম ফিউমিগেশন, পরীক্ষিত ব্রিডার',
 array['CHICKEN','DUCK','TURKEY','QUAIL'],31),
('COLIBACILLOSIS','কলিব্যাসিলোসিস (ই.কোলাই)','Colibacillosis','bacterial',false,false,true,
 'নাভি পচা, পেটে পানি, শ্বাসকষ্ট, হঠাৎ মৃত্যু',
 'পরিষ্কার পানি, লিটার শুকনো রাখা',array['CHICKEN','DUCK','QUAIL','TURKEY'],32),
('FOWL_CHOLERA','ফাউল কলেরা','Fowl Cholera','bacterial',false,false,true,
 'ঝুঁটি নীলচে, ফোলা, হঠাৎ মৃত্যু, হলুদ-সবুজ পায়খানা',
 '১০–১২ সপ্তাহে টিকা; ইঁদুর ও বন্য পাখি নিয়ন্ত্রণ',
 array['CHICKEN','DUCK','TURKEY'],33),
('CORYZA','করাইজা','Infectious Coryza','bacterial',false,false,true,
 'মুখ ও চোখ ফোলা, দুর্গন্ধযুক্ত নাকের পানি','টিকা ও বায়োসিকিউরিটি',array['CHICKEN'],34),
('NECROTIC_ENT','নেক্রোটিক এন্টারাইটিস','Necrotic Enteritis','bacterial',false,false,true,
 'গাঢ় দুর্গন্ধযুক্ত পায়খানা, হঠাৎ মৃত্যু, অন্ত্রে ঘা',
 'খাদ্যে হঠাৎ পরিবর্তন এড়ানো, ককসিডিওসিস নিয়ন্ত্রণ',array['CHICKEN'],35),
('OMPHALITIS','নাভি পচা','Omphalitis','bacterial',false,false,false,
 'নাভি ভেজা ও দুর্গন্ধযুক্ত, বাচ্চা ঝিমায়','হ্যাচারির পরিচ্ছন্নতা',
 array['CHICKEN','DUCK','TURKEY','QUAIL'],36),
-- ═══════ পরজীবী ও ছত্রাক ═══════
('COCCIDIOSIS','ককসিডিওসিস','Coccidiosis','protozoal',false,false,true,
 'রক্তমিশ্রিত পায়খানা, ঝিমানো, পালক উস্কোখুস্কো',
 'লিটার শুকনো রাখা, কক্সিডিওস্ট্যাট, ভিড় কমানো',
 array['CHICKEN','DUCK','TURKEY','QUAIL','RABBIT','GOAT','SHEEP','CATTLE'],40),
('WORM_POULTRY','কৃমি (পাখি)','Helminthiasis (Poultry)','parasitic',false,false,false,
 'ওজন কমা, পালক নষ্ট, ডিম কমা','নিয়মিত কৃমিনাশক, লিটার ব্যবস্থাপনা',
 array['CHICKEN','DUCK','TURKEY','QUAIL','PIGEON'],41),
('LICE_MITE','উকুন ও মাইট','Lice & Mites','parasitic',false,false,true,
 'অস্থিরতা, পালক খুঁটে ফেলা, রক্তশূন্যতা','ঘর ও খাঁচা কীটনাশক দিয়ে পরিষ্কার',
 array['CHICKEN','DUCK','TURKEY','QUAIL','PIGEON'],42),
('ASPERGILLOSIS','অ্যাসপারজিলোসিস (ব্রুডার নিউমোনিয়া)','Aspergillosis','fungal',false,false,false,
 'হাঁ করে শ্বাস, ঝিমানো, বাচ্চায় মৃত্যু','ভেজা/ছাতাপড়া লিটার ও খাদ্য এড়ানো',
 array['CHICKEN','DUCK','TURKEY','QUAIL'],43),
('AFLATOXICOSIS','অ্যাফ্লাটক্সিন বিষক্রিয়া','Aflatoxicosis','toxic',false,false,false,
 'বৃদ্ধি থেমে যাওয়া, যকৃত নষ্ট, ডিম কমা, রোগ প্রতিরোধ ভেঙে পড়া',
 'ভালো ভুট্টা/খৈল, শুকনো গুদাম, টক্সিন বাইন্ডার',
 array['CHICKEN','DUCK','TURKEY','QUAIL','CATTLE','GOAT'],44),
-- ═══════ পুষ্টি, বিপাক ও পরিবেশ ═══════
('HEAT_STRESS','হিট স্ট্রেস (গরমে কষ্ট)','Heat Stress','environmental',false,false,false,
 'হাঁপানো, ডানা ছড়িয়ে বসা, পানি বেশি খাওয়া, খাওয়া কমা, হঠাৎ মৃত্যু',
 'দুপুরে খাবার বন্ধ, প্রচুর ঠান্ডা পানি, ফগার/ভেজা চটের পর্দা, ভিটামিন-সি ও ইলেকট্রোলাইট',
 array['CHICKEN','DUCK','QUAIL','TURKEY','CATTLE','BUFFALO','GOAT','SHEEP','RABBIT'],50),
('COLD_STRESS','ঠান্ডায় কষ্ট','Cold Stress','environmental',false,false,false,
 'একসাথে জড়ো হওয়া, ঝিমানো, ডায়রিয়া','ব্রুডারের তাপ ঠিক রাখা, পর্দা দেওয়া',
 array['CHICKEN','DUCK','QUAIL','GOAT','CATTLE'],51),
('PILING','চাপাচাপিতে মৃত্যু','Piling / Suffocation','traumatic',false,false,false,
 'এক কোণে জড়ো হয়ে চাপা পড়া','আলো ঠিক রাখা, ভিড় কমানো, হঠাৎ শব্দ এড়ানো',
 array['CHICKEN','DUCK','QUAIL'],52),
('ASCITES','পেটে পানি জমা','Ascites','metabolic',false,false,false,
 'পেট ফোলা, শ্বাসকষ্ট, ঝুঁটি নীলচে','দ্রুত বৃদ্ধি নিয়ন্ত্রণ, ভালো বায়ু চলাচল',array['CHICKEN'],53),
('SDS','হঠাৎ মৃত্যু সিনড্রোম','Sudden Death Syndrome','metabolic',false,false,false,
 'সুস্থ পাখি চিৎ হয়ে হঠাৎ মরে যায়','খাদ্য ব্যবস্থাপনা ও আলো নিয়ন্ত্রণ',array['CHICKEN'],54),
('RICKETS','রিকেটস','Rickets','nutritional',false,false,false,
 'পা বেঁকে যাওয়া, হাড় নরম, চলতে না পারা','ক্যালসিয়াম-ফসফরাস ও ভিটামিন ডি৩ ঠিক রাখা',
 array['CHICKEN','DUCK','QUAIL','TURKEY'],55),
('PROLAPSE','ডিম্বনালী বেরিয়ে আসা','Prolapse','metabolic',false,false,false,
 'পায়ুপথ দিয়ে লাল মাংস বেরিয়ে আসা, অন্য মুরগি ঠোকরায়',
 'অতিরিক্ত ওজন এড়ানো, আলোর সময়সূচি ঠিক রাখা',array['CHICKEN','DUCK'],56),
('CAGE_FATIGUE','কেজ লেয়ার ফ্যাটিগ','Cage Layer Fatigue','nutritional',false,false,false,
 'পা অবশ, খাঁচায় শুয়ে পড়া','ক্যালসিয়াম ও ভিটামিন ডি৩',array['CHICKEN'],57),
-- ═══════ গরু ও মহিষ ═══════
('FMD','ক্ষুরারোগ','Foot and Mouth Disease (FMD)','viral',true,false,true,
 'মুখে ও ক্ষুরে ঘা, লালা ঝরা, খোঁড়ানো, খাওয়া বন্ধ, দুধ কমে যাওয়া',
 'বছরে দুইবার FMD টিকা; নতুন প্রাণী কোয়ারেন্টাইন',
 array['CATTLE','BUFFALO','GOAT','SHEEP'],60),
('ANTHRAX','তড়কা','Anthrax','bacterial',true,true,true,
 'হঠাৎ মৃত্যু, নাক-মুখ-পায়ুপথে কালচে রক্ত জমাট বাঁধে না',
 'বার্ষিক টিকা। মৃতদেহ কাটা বা চামড়া ছাড়ানো সম্পূর্ণ নিষেধ — মানুষের জন্য মারাত্মক। চুন দিয়ে গভীর গর্তে পুঁতে ফেলুন',
 array['CATTLE','BUFFALO','GOAT','SHEEP'],61),
('BQ','বাদলা','Black Quarter (BQ)','bacterial',true,false,true,
 'পিছনের রানে ফোলা, চাপ দিলে খসখস শব্দ, প্রচণ্ড জ্বর, খোঁড়ানো',
 '৬ মাস–২ বছর বয়সে বার্ষিক টিকা',array['CATTLE','BUFFALO'],62),
('HS','গলাফুলা','Haemorrhagic Septicaemia (HS)','bacterial',true,false,true,
 'গলা ও গলকম্বল ফুলে যাওয়া, শ্বাসকষ্ট, উঁচু জ্বর, দ্রুত মৃত্যু',
 'বার্ষিক টিকা, বর্ষার আগে',array['CATTLE','BUFFALO'],63),
('LSD','লাম্পি স্কিন ডিজিজ','Lumpy Skin Disease','viral',true,false,true,
 'সারা গায়ে শক্ত গুটি, জ্বর, চোখ-নাক দিয়ে পানি, দুধ কমা',
 'LSD টিকা; মশা-মাছি ও টিক নিয়ন্ত্রণ',array['CATTLE','BUFFALO'],64),
('BRUCELLOSIS','ব্রুসেলোসিস','Brucellosis','bacterial',true,true,true,
 'গর্ভের শেষ দিকে গর্ভপাত, ফুল না পড়া, বারবার প্রজননে ব্যর্থতা',
 'পরীক্ষা করে আক্রান্ত প্রাণী সরানো; দুধ ফুটিয়ে খাওয়া',
 array['CATTLE','BUFFALO','GOAT','SHEEP'],65),
('MASTITIS','ওলান প্রদাহ','Mastitis','bacterial',false,false,false,
 'ওলান গরম ও শক্ত, দুধে চাকা বা রক্ত, দুধ কমা',
 'দোহনের আগে-পরে ওলান পরিষ্কার, টিট ডিপিং, শুকনো বিছানা',
 array['CATTLE','BUFFALO','GOAT'],66),
('MILK_FEVER','দুগ্ধজ্বর','Milk Fever (Hypocalcaemia)','metabolic',false,false,false,
 'প্রসবের পরপর উঠে দাঁড়াতে না পারা, ঘাড় বেঁকে যাওয়া, ঠান্ডা কান',
 'গর্ভের শেষ দিকে ক্যালসিয়াম নিয়ন্ত্রণ, প্রসবের পর ক্যালসিয়াম',
 array['CATTLE','BUFFALO','GOAT'],67),
('KETOSIS','কিটোসিস','Ketosis','metabolic',false,false,false,
 'খাওয়া কমা, দুধ কমা, শ্বাসে মিষ্টি গন্ধ','প্রসবের পর যথেষ্ট শক্তিদায়ক খাদ্য',
 array['CATTLE','BUFFALO','GOAT'],68),
('BLOAT','পেট ফোলা','Bloat (Tympany)','metabolic',false,false,false,
 'বাম পাশের পেট ফুলে ওঠা, শ্বাসকষ্ট, অস্থিরতা',
 'হঠাৎ প্রচুর কাঁচা ঘাস/ডাল জাতীয় ঘাস না খাওয়ানো',
 array['CATTLE','BUFFALO','GOAT','SHEEP'],69),
('TICK_BORNE','রক্তবাহিত রোগ (থাইলেরিয়া/ব্যাবেসিয়া)','Tick-borne (Theileria/Babesia)','protozoal',false,false,true,
 'উঁচু জ্বর, রক্তশূন্যতা, লাল প্রস্রাব, লসিকা গ্রন্থি ফোলা',
 'টিক নিয়ন্ত্রণ, নিয়মিত অ্যাকারিসাইড',array['CATTLE','BUFFALO'],70),
('LIVER_FLUKE','যকৃত কৃমি','Liver Fluke (Fascioliasis)','parasitic',false,false,false,
 'ধীরে ধীরে শুকিয়ে যাওয়া, চোয়ালের নিচে পানি জমা (বোতল চোয়াল)',
 'ভেজা জমিতে চারণ এড়ানো, বছরে দুইবার কৃমিনাশক',
 array['CATTLE','BUFFALO','GOAT','SHEEP'],71),
('WORM_RUMINANT','কৃমি (গবাদি)','Helminthiasis (Ruminant)','parasitic',false,false,false,
 'শুকিয়ে যাওয়া, পাতলা পায়খানা, লোম উস্কোখুস্কো, রক্তশূন্যতা',
 'প্রতি ৩–৪ মাসে কৃমিনাশক; বিশেষত বর্ষার পরে',
 array['CATTLE','BUFFALO','GOAT','SHEEP','RABBIT'],72),
('RETAINED_PLACENTA','ফুল না পড়া','Retained Placenta','metabolic',false,false,false,
 'প্রসবের ১২ ঘণ্টা পরেও ফুল ঝুলে থাকা, দুর্গন্ধ',
 'গর্ভকালীন সুষম খাদ্য, খনিজ ও সেলেনিয়াম',array['CATTLE','BUFFALO','GOAT'],73),
('REPEAT_BREEDING','বারবার প্রজননে ব্যর্থতা','Repeat Breeding','metabolic',false,false,false,
 'তিনবারের বেশি প্রজননেও গর্ভধারণ হয় না',
 'সঠিক সময়ে প্রজনন, জরায়ু সংক্রমণের চিকিৎসা, খনিজ',
 array['CATTLE','BUFFALO','GOAT'],74),
('CALF_SCOUR','বাছুরের ডায়রিয়া','Calf Scour','bacterial',false,false,true,
 'পাতলা সাদা/হলুদ পায়খানা, পানিশূন্যতা, দুর্বলতা',
 'জন্মের ২ ঘণ্টার মধ্যে শালদুধ, পরিষ্কার বাসস্থান',
 array['CATTLE','BUFFALO','GOAT','SHEEP'],75),
('FOOT_ROT','খুর পচা','Foot Rot','bacterial',false,false,true,
 'খোঁড়ানো, খুরের ফাঁকে দুর্গন্ধযুক্ত ঘা','শুকনো মেঝে, ফুট বাথ',
 array['CATTLE','BUFFALO','GOAT','SHEEP'],76),
-- ═══════ ছাগল ও ভেড়া ═══════
('PPR','পিপিআর (ছাগলের প্লেগ)','Peste des Petits Ruminants (PPR)','viral',true,false,true,
 'উঁচু জ্বর, মুখে ঘা, নাক-চোখ দিয়ে পানি, তীব্র ডায়রিয়া, উচ্চ মৃত্যুহার',
 '৩ মাস বয়সে PPR টিকা, এরপর প্রতি ৩ বছরে',array['GOAT','SHEEP'],80),
('GOAT_POX','ছাগলের বসন্ত','Goat Pox','viral',false,false,true,
 'চামড়ায় গুটি, জ্বর, বাচ্চায় বেশি মৃত্যু','টিকা ও আলাদা রাখা',array['GOAT','SHEEP'],81),
('CCPP','ছাগলের নিউমোনিয়া (CCPP)','Contagious Caprine Pleuropneumonia','bacterial',false,false,true,
 'কাশি, দ্রুত শ্বাস, জ্বর, ঘাড় বাড়িয়ে শ্বাস নেওয়া',
 'ভিড় কমানো, বায়ু চলাচল, টিকা',array['GOAT'],82),
('ENTEROTOXAEMIA','এন্টারোটক্সিমিয়া','Enterotoxaemia','bacterial',false,false,false,
 'হঠাৎ মৃত্যু, খিঁচুনি, পেট ফোলা','হঠাৎ দানাদার খাদ্য বাড়ানো এড়ানো, টিকা',
 array['GOAT','SHEEP'],83),
('TETANUS','ধনুষ্টংকার','Tetanus','bacterial',false,true,false,
 'শরীর শক্ত, চোয়াল আটকে যাওয়া, খিঁচুনি','খাসি করা বা ক্ষতের সময় পরিচ্ছন্নতা ও টিকা',
 array['GOAT','SHEEP','CATTLE','BUFFALO'],84),
('PNEUMONIA','নিউমোনিয়া','Pneumonia','bacterial',false,false,true,
 'কাশি, দ্রুত শ্বাস, নাক দিয়ে পানি, জ্বর','ভেজা-ঠান্ডা থেকে রক্ষা, বায়ু চলাচল',
 array['GOAT','SHEEP','CATTLE','BUFFALO','RABBIT'],85),
-- ═══════ সাধারণ (সব প্রজাতি) ═══════
('RABIES','জলাতঙ্ক','Rabies','viral',true,true,true,
 'আচরণ বদলে যাওয়া, অতিরিক্ত লালা, আক্রমণাত্মক বা অবশ হয়ে যাওয়া',
 'কুকুর-শিয়ালের কামড় থেকে রক্ষা, কামড়ালে সাথে সাথে টিকা',
 array['CATTLE','BUFFALO','GOAT','SHEEP','RABBIT'],90),
('PREDATION_CAUSE','শিয়াল/কুকুর/বেজিতে নেওয়া','Predation','predation',false,false,false,
 'রাতে প্রাণী নিখোঁজ, আঁচড়-কামড়ের দাগ, পালক ছড়ানো',
 'রাতে ঘর বন্ধ, জাল ও বেড়া, আলো, পাহারা',
 array['CHICKEN','DUCK','MUSCOVY','GOOSE','QUAIL','PIGEON','TURKEY','GUINEA_FOWL','GOAT','SHEEP','RABBIT'],91),
('DROWNING','পানিতে ডুবে মৃত্যু','Drowning','traumatic',false,false,false,
 'পুকুর/নালায় ডুবে যাওয়া — বিশেষত বাচ্চা ও বর্ষায়',
 'পুকুরের ধারে বেড়া, বাচ্চা আলাদা রাখা',
 array['CHICKEN','DUCK','QUAIL','GOAT','CATTLE'],92),
('POISONING','বিষক্রিয়া','Poisoning','toxic',false,false,false,
 'হঠাৎ খিঁচুনি, লালা, ডায়রিয়া, দ্রুত মৃত্যু',
 'কীটনাশক ছেটানো জমিতে চারণ নিষেধ, বিষাক্ত গাছ চেনা',
 array['CATTLE','BUFFALO','GOAT','SHEEP','CHICKEN','DUCK'],93),
('SNAKE_BITE','সাপে কাটা','Snake Bite','traumatic',false,false,false,
 'পা বা মুখ ফুলে যাওয়া, দুই দাঁতের দাগ','ঘরের আশপাশ পরিষ্কার, ইঁদুর নিয়ন্ত্রণ',
 array['CATTLE','BUFFALO','GOAT','SHEEP','CHICKEN','DUCK'],94),
('LIGHTNING','বজ্রপাত','Lightning Strike','traumatic',false,false,false,
 'মাঠে হঠাৎ মৃত্যু, পোড়ার দাগ','ঝড়ের সময় মাঠ থেকে ফিরিয়ে আনা',
 array['CATTLE','BUFFALO','GOAT','SHEEP'],95),
('ACCIDENT','দুর্ঘটনা/আঘাত','Accident / Injury','traumatic',false,false,false,
 'হাড় ভাঙা, কেটে যাওয়া, পড়ে যাওয়া','নিরাপদ মেঝে, পরিবহনে সতর্কতা',null,96),
('CULL_LOW_YIELD','কালিং — কম উৎপাদন','Culling — Low Yield','culling',false,false,false,
 null,null,null,97),
('CULL_SICK','কালিং — দীর্ঘস্থায়ী অসুস্থতা','Culling — Chronic Illness','culling',false,false,false,
 null,null,null,98),
('CULL_AGE','কালিং — বয়স','Culling — Old Age','culling',false,false,false,null,null,null,99),
('UNKNOWN','অজানা কারণ','Unknown Cause','unknown',false,false,false,
 null,'কারণ না জানা গেলে পোস্ট-মর্টেম করান — পরের ব্যাচ বাঁচবে',null,100);

insert into master.disease
  (disease_code, name_bn, name_en, cause_type, is_notifiable, is_zoonotic, is_contagious,
   typical_signs_bn, prevention_bn, sort_order)
select d.disease_code, d.name_bn, d.name_en, d.cause_type, d.notifiable, d.zoonotic,
       d.contagious, d.signs_bn, d.prevention_bn, d.sort_order
from _dz d
where not exists (select 1 from master.disease x
  where x.organization_no is null and x.disease_code = d.disease_code::citext);

-- প্রজাতি সংযোগ (species_codes NULL হলে সব প্রজাতিতে প্রযোজ্য — সারি লাগে না)
insert into master.disease_species (disease_no, species_no)
select dz.disease_no, s.species_no
from _dz d
join master.disease dz on dz.organization_no is null and dz.disease_code = d.disease_code::citext
cross join lateral unnest(d.species_codes) as sc(code)
join master.species s on s.organization_no is null and s.species_code = sc.code::citext
where d.species_codes is not null
  and not exists (select 1 from master.disease_species x
    where x.disease_no = dz.disease_no and x.species_no = s.species_no);

drop table _dz;
